parameters:
    exception_handler: Yolo\handleException

services:
    http_kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments:
            - @dispatcher
            - @controller_resolver

    dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver

    route_builder:
        class: Yolo\RouteBuilder
        arguments:
            - @routes

    routes:
        class: Symfony\Component\Routing\RouteCollection

    url_matcher:
        class: Symfony\Component\Routing\Matcher\UrlMatcher
        arguments:
            - @routes
            - @request_context

    request_context:
        class: Symfony\Component\Routing\RequestContext

    listener.router:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
            - @url_matcher
            - @request_context
        tags:
            - { name: kernel.event_subscriber }

    listener.response:
        class: Symfony\Component\HttpKernel\EventListener\ResponseListener
        arguments:
            - UTF-8
        tags:
            - { name: kernel.event_subscriber }

    listener.exception:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
            - %exception_handler%
        tags:
            - { name: kernel.event_subscriber }
